name: Doc Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: langroodi/doxygenize@v1.6.1
        with:
          htmloutput: './html/'
        
