- name: arduino/arduino-lint-action
  uses: arduino/arduino-lint-action@v1.0.1
  
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
